use_frameworks!

platform :ios, '9.0'

target 'TestDemo_Example' do
  pod 'TestDemo', :path => '../'
  pod 'AFNetworking', '~> 4.0'

  target 'TestDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
